definitions:
  dto.CreateArticleRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  dto.CreateArticleTagRequest:
    properties:
      article_id:
        type: integer
      tag_id:
        type: integer
    type: object
  dto.CreateCommentRequest:
    properties:
      article_id:
        type: integer
      content:
        type: string
    type: object
  dto.CreateTagRequest:
    properties:
      name:
        type: string
      slug:
        type: string
    type: object
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.UpdateArticleRequest:
    properties:
      active:
        type: boolean
      content:
        type: string
      title:
        type: string
    type: object
  models.Article:
    properties:
      active:
        type: boolean
      content:
        type: string
      createdAt:
        type: string
      id:
        format: int64
        type: integer
      title:
        type: string
      userID:
        format: int64
        type: integer
      viewCount:
        format: int64
        type: integer
    type: object
  models.ArtilceTag:
    properties:
      article_id:
        type: integer
      tag_id:
        type: integer
    type: object
  models.Comments:
    properties:
      article_id:
        type: integer
      content:
        type: string
      create_at:
        type: string
      id:
        type: integer
      user_id:
        type: integer
    type: object
  models.Follows:
    properties:
      follower_id:
        type: integer
      following_id:
        type: integer
    type: object
  models.Tag:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    type: object
info:
  contact: {}
paths:
  /article-tags:
    get:
      parameters:
      - description: Article ID
        in: query
        name: article_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ArtilceTag'
            type: array
      summary: Article taglarini ko'rish
      tags:
      - ArticleTags
  /article-tags/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Article va Tag ID
        in: body
        name: article_tag
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArticleTagRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Tag qo'shildi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Articlega tag qo'shish
      tags:
      - ArticleTags
  /article-tags/delete:
    delete:
      parameters:
      - description: Article ID
        in: query
        name: article_id
        required: true
        type: integer
      - description: Tag ID
        in: query
        name: tag_id
        required: true
        type: integer
      responses:
        "200":
          description: Tag o'chirildi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Articledan tag o'chirish
      tags:
      - ArticleTags
  /articles:
    get:
      description: Ma'lumotlar bazasidan barcha maqolalar ro'yxatini qaytaradi
      produces:
      - application/json
      responses:
        "200":
          description: Maqolalar ro'yxati muvaffaqiyatli qaytarildi
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "500":
          description: Ichki server xatosi
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Barcha maqolalarni olish
      tags:
      - articles
  /articles/create:
    post:
      consumes:
      - application/json
      description: Title va content bilan yangi article yaratadi
      parameters:
      - description: Article ma'lumotlari
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: muvafaqiyatli qo'shildi
          schema:
            type: string
        "400":
          description: Noto'g'ri so'rov
          schema:
            type: string
        "500":
          description: Server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Yangi article yaratish
      tags:
      - articles
  /articles/delete:
    delete:
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: o'chirildi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
        "500":
          description: server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Article o'chirish
      tags:
      - articles
  /articles/get:
    get:
      description: Malumotlar bazasidan bitta maqolani qaytaradi
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: maqola  muvaffaqiyatli qaytarildi
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "500":
          description: Ichki server xatosi
          schema:
            additionalProperties:
              type: string
            type: object
      summary: bitta Article o'qish
      tags:
      - articles
  /articles/update:
    put:
      consumes:
      - application/json
      description: Article title, content va active holatini yangilaydi
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      - description: Article ma'lumotlari
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: yangilandi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
        "500":
          description: server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Article yangilash
      tags:
      - articles
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Email va parol bilan kirish, token qaytaradi
      parameters:
      - description: Email va parol
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Foydalanuvchi kirishi (Sign In)
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Yangi foydalanuvchini bazaga qo'shadi va token qaytaradi
      parameters:
      - description: Foydalanuvchi ma'lumotlari
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Foydalanuvchi yaratish (Sign Up)
      tags:
      - Auth
  /comments:
    get:
      parameters:
      - description: Article ID
        in: query
        name: article_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Comments'
            type: array
      summary: Maqola commentlari
      tags:
      - Comments
  /comments/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Comment ma'lumotlari
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Comments'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Comment yaratish
      tags:
      - Comments
  /comments/delete:
    delete:
      parameters:
      - description: Comment ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: o'chirildi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Comment o'chirish
      tags:
      - Comments
  /follows/follow:
    post:
      consumes:
      - application/json
      parameters:
      - description: Following ID
        in: query
        name: following_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: follow qilindi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Follow qilish
      tags:
      - follows
  /follows/followers:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Follows'
            type: array
      summary: Obunachlarni ko'rish
      tags:
      - follows
  /follows/following:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Follows'
            type: array
      summary: Following larni ko'rish
      tags:
      - follows
  /follows/unfollow:
    delete:
      parameters:
      - description: Following ID
        in: query
        name: following_id
        required: true
        type: integer
      responses:
        "200":
          description: unfollow qilindi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Unfollow qilish
      tags:
      - follows
  /tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tag'
            type: array
      summary: Barcha taglar
      tags:
      - Tags
  /tags/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Tag ma'lumotlari
        in: body
        name: tag
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTagRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Tag'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      - BearerAuth: []
      summary: Tag yaratish
      tags:
      - Tags
  /tags/delete:
    delete:
      parameters:
      - description: Tag ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: o'chirildi
          schema:
            type: string
      security:
      - BearerAuth: []
      - BearerAuth: []
      summary: Tag o'chirish
      tags:
      - Tags
  /tags/get:
    get:
      parameters:
      - description: Tag ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tag'
      summary: Bitta tag
      tags:
      - Tags
securityDefinitions:
  BearerAuth:
    description: Blog loyihasi API
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
