definitions:
  dto.CreateArticleRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  dto.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.UpdateArticleRequest:
    properties:
      active:
        type: boolean
      content:
        type: string
      title:
        type: string
    type: object
  models.Article:
    properties:
      active:
        type: boolean
      content:
        type: string
      createdAt:
        type: string
      id:
        format: int64
        type: integer
      title:
        type: string
      userID:
        format: int64
        type: integer
      viewCount:
        format: int64
        type: integer
    type: object
info:
  contact: {}
paths:
  /articles:
    get:
      description: Ma'lumotlar bazasidan barcha maqolalar ro'yxatini qaytaradi
      produces:
      - application/json
      responses:
        "200":
          description: Maqolalar ro'yxati muvaffaqiyatli qaytarildi
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "500":
          description: Ichki server xatosi
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Barcha maqolalarni olish
      tags:
      - articles
  /articles/create:
    post:
      consumes:
      - application/json
      description: Title va content bilan yangi article yaratadi
      parameters:
      - description: Article ma'lumotlari
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/dto.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: muvafaqiyatli qo'shildi
          schema:
            type: string
        "400":
          description: Noto'g'ri so'rov
          schema:
            type: string
        "500":
          description: Server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Yangi article yaratish
      tags:
      - articles
  /articles/delete:
    delete:
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: o'chirildi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
        "500":
          description: server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Article o'chirish
      tags:
      - articles
  /articles/get:
    get:
      description: Malumotlar bazasidan bitta maqolani qaytaradi
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: maqola  muvaffaqiyatli qaytarildi
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
        "500":
          description: Ichki server xatosi
          schema:
            additionalProperties:
              type: string
            type: object
      summary: bitta Article o'qish
      tags:
      - articles
  /articles/update:
    put:
      consumes:
      - application/json
      description: Article title, content va active holatini yangilaydi
      parameters:
      - description: Article ID
        in: query
        name: id
        required: true
        type: integer
      - description: Article ma'lumotlari
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: yangilandi
          schema:
            type: string
        "400":
          description: id noto'g'ri
          schema:
            type: string
        "500":
          description: server xatosi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Article yangilash
      tags:
      - articles
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Email va parol bilan kirish, token qaytaradi
      parameters:
      - description: Email va parol
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Foydalanuvchi kirishi (Sign In)
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Yangi foydalanuvchini bazaga qo'shadi va token qaytaradi
      parameters:
      - description: Foydalanuvchi ma'lumotlari
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Foydalanuvchi yaratish (Sign Up)
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    description: Blog loyihasi API
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
